# spring 配置
spring:
  # 数据源配置
  datasource:
    # JDBC驱动类签名
    driverClassName: com.mysql.cj.jdbc.Driver
    # 连接数据库URL路径
    url:
    # 数据库账户名称
    username:
    # 数据库账户密码
    password:
    # 获取Connection连接对象的类签名
    type: com.alibaba.druid.pool.DruidDataSource
    # Redis配置
  redis:
    # Redis部署Ip地址
    host:
    # Redis监听端口
    port:
    # Redis登录密码
    password:
    # kafka 配置
  kafka:
    # kafka 服务节点网络域
    bootstrap-servers: 
    # 生产者 配置
    producer:
      # 重试次数
      retries: 3
      # 批量发送数据大小
      batch-size: 16384
      # 缓冲数据大小
      buffer-memory: 33554432
      # 回执数
      acks: 1
      # key数据 对象序列化 类签名
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # value数据 对象序列化 类签名
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    # 消费者 配置
    consumer:
      # 消费者分组id
      group-id: group-01
      # 启用自动提交回执
      enable-auto-commit: false
      # 重置消费队列指针策略
      auto-offset-reset: earliest
      # key数据 对象反序列化 类签名
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # value数据 对象反序列化 类签名
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 队列池中的最大记录数
      max-poll-records: 500
    # 监听器 配置
    listener:
      # 回执模式：手动回执模式
      ack-mode: MANUAL_IMMEDIATE
# mybatis配置
mybatis:
  # 映射文件表达式
  mapper-locations: classpath:mapper/*Mapper.xml
# mybatis-plus 配置信息
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
# 自定 设置sms参数
ali-sms:
  access-key-id:
  access-key-secret:
  endpoint:
  sign-name:
  register-template-code:
es:
  host-and-port:
